title: My Experimental Jekyll Site 
email: github@zuijlen.eu
description: >- # this means to ignore newlines until "baseurl:"
   Hier staat een verhaaltje dat ik neer kan zetten. Dit staat in _config.yml
   geconfigureerd. Dit kan ik over meerdere 
   regels
   spreiden
   als ik wil.
   En dat komt gewoon goed op de site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://testtest.zuijlen.eu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: remco72
github_username:  remcovz
timezone: Europe/Amsterdam
collections:
  albums:
    output: true
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
paginate: 5

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
- jekyll-include-cache
sass:
  sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - CNAME
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
